; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
lib_ldf_mode = deep+
build_flags = 
    -D SIMULATION
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D TINY_GSM_MODEM_SIM7600
    -D TINY_GSM_RX_BUFFER=1024
lib_deps =
    milesburton/DallasTemperature@^3.11.0
    paulstoffregen/OneWire@^2.3.7
    https://github.com/mandulaj/PZEM-004T-v30.git
    adafruit/Adafruit ADS1X15@^2.5.0
    SPI
    https://github.com/Hard-Stuff/TinyGSM.git
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.1.0
    arduino-libraries/ArduinoHttpClient@^0.6.1
    https://github.com/DFRobot/DFRobot_IICSerial.git

[env:esp32dev-reel]
platform = espressif32
board = esp32dev
upload_port = COM3
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D TINY_GSM_MODEM_A76XXSSL
    -D TINY_GSM_RX_BUFFER=1024
lib_deps =
    milesburton/DallasTemperature@^3.11.0
    paulstoffregen/OneWire@^2.3.7
    https://github.com/mandulaj/PZEM-004T-v30.git
    adafruit/Adafruit ADS1X15@^2.5.0
    SPI
    https://github.com/lewisxhe/TinyGSM-fork.git
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson@^7.1.0
    arduino-libraries/ArduinoHttpClient@^0.6.1
    https://github.com/DFRobot/DFRobot_IICSerial.git

[env:esp32dev-reel-scenario]
extends = env:esp32dev-reel
monitor_speed = 115200

build_flags =
    ${env:esp32dev-reel.build_flags}
    -D SCENARIO_MQTT_TEST